name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code source
        uses: actions/checkout@v4

      - name: Construire l'image Docker
        run: |
          docker build -t shyamsubrun/hello-world-node:${{ github.sha }} .

      - name: Connexion à Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pousser l'image Docker
        run: |
          docker tag shyamsubrun/hello-world-node:${{ github.sha }} shyamsubrun/hello-world-node:latest
          docker push shyamsubrun/hello-world-node:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Déployer sur Kubernetes
        run: |
          kubectl set image deployment/hello-world-node hello-world-node=shyamsubrun/hello-world-node:latest --record
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}
 