name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code source
        uses: actions/checkout@v4

      - name: Construire l'image Docker
        run: |
          docker build -t shyamsubrun/hello-world-node:${{ github.sha }} .

      - name: Connexion à Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pousser l'image Docker
        run: |
          docker tag shyamsubrun/hello-world-node:${{ github.sha }} shyamsubrun/hello-world-node:latest
          docker push shyamsubrun/hello-world-node:latest
