name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code source
        uses: actions/checkout@v4

      - name: Construire l'image Docker
        run: |
          docker build -t shyamsubrun/hello-world-node:${{ github.sha }} .

      - name: Connexion à Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pousser l'image Docker
        run: |
          docker tag shyamsubrun/hello-world-node:${{ github.sha }} shyamsubrun/hello-world-node:latest
          docker push shyamsubrun/hello-world-node:latest
      
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installer Kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.17.0/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Démarrer un cluster Kubernetes avec Kind
        run: |
          kind create cluster --name my-cluster

      - name: Vérifier le cluster Kind
        run: |
          kind get clusters

      - name: Vérifier le contexte Kubernetes
        run: |
          kubectl config get-contexts
          kubectl config current-context

      - name: Vérifier le cluster
        run: |
          kubectl cluster-info
          kubectl get nodes

      - name: Déployer l'application avec deployment.yaml
        run: |
          kubectl apply -f deployment.yaml

      - name: Déployer sur Kubernetes (mettre à jour l'image)
        run: |
          kubectl set image deployment/hello-world-node hello-world-node=shyamsubrun/hello-world-node:latest
